apiVersion: v1
kind: Service
metadata:
  name: showcase-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: showcase-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard
  volumeName: "mysql-pv"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: showcase-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: showcase-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showcase-mysql
  template:
    metadata:
      labels:
        app: showcase-mysql
    spec:
      containers:
        - name: mysql
          image: tobi312/rpi-mariadb:10.1
          ports:
            - name: db-port
              containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

