apiVersion: v1
kind: Service
metadata:
  name: showcase-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: showcase-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: standard
  volumeName: "mysql-pv"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: showcase-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: showcase-mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: showcase-mysql
spec:
  selector:
    matchLabels:
      app: showcase-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: showcase
    spec:
      containers:
        - image: tobi312/rpi-mariadb:10.1
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

